---
# tasks file for docker

- name: apt-get update
  apt:
    update_cache: yes

- name: Installing useful and necessary packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - gnupg-agent
    - htop
    - python-pip

- name: Adding Docker CE Key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adding Docker CE repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu '{{ ansible_facts['lsb']['codename'] }}' stable"
    update_cache: yes

- name: apt-get update
  apt:
    update_cache: yes

- name: Installing Docker CE
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce

- name: Installing Docker compose
  get_url:
     url: https://github.com/docker/compose/releases/download/1.18.0/docker-compose-Linux-x86_64
     dest: /usr/local/bin/docker-compose
     mode: 0755

- name: Starting Docker CE
  systemd:
    state: started
    name: docker

- name: Enable Docker CE 
  systemd:
    name: docker
    enabled: yes
    masked: no

- name: Installing Weave Network
  get_url:
    url: http://git.io/weave
    dest: /usr/local/bin/weave
    mode: 0755








    

